services:
  redis:
    image: redis:8.4-alpine
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    # depends_on:
    #   - redis
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build:  
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    env_file:
      - ./frontend/.env
    restart: always
    ports:
      - "5175:80"

volumes:
  redis_data:
