services:
  redis:
    image: redis:8.4-alpine
    container_name: redis
    command: redis-server --appendonly yes --maxmemory-policy noeviction
    volumes:
      - redis_data:/data
    restart: always
    ports:
      - "6379:6379"

  sleek-ai-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
    container_name: sleek-ai-app
    env_file:
      - ./apps/backend/.env
    depends_on:
      - redis
    ports:
      - "3000:3000"
    restart: always

  sleek-ai-worker:
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
    container_name: sleek-ai-worker
    env_file:
      - ./apps/worker/.env
    depends_on:
      - redis
    restart: always

volumes:
  redis_data:
